Repository slateci/slate-portal, pull requests merged in 2023-05, with the labels that each got.

#273 Update news tab
  portal/static/news.md
Labels: enhancement

#274 272 add lint checks to pull requests
  .github/workflows/pr-python.yml
  pyproject.toml
  resources/docker/environment.yml
  resources/docker/requirements.txt
  resources/docs/index.md
  resources/docs/static-code-analysis.md
  setup.cfg
Labels: infrastruture

#278 277 apply black python code formatting suggestions
  .github/workflows/pr-python.yml
  portal/__init__.py
  portal/connect_api.py
  portal/decorators.py
  portal/logtools.py
  portal/utils.py
  portal/views.py
  portal/views/views_about.py
  portal/views/views_applications.py
  portal/views/views_clusters.py
  portal/views/views_error_handling.py
  portal/views/views_groups.py
  portal/views/views_instances.py
  portal/views/views_webhooks.py
  resources/docs/static-code-analysis.md
Labels: enhancement

#281 Updated reusable github workflow refs to v16.
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/integration-tests.yml
  .github/workflows/pr-chart.yml
  .github/workflows/pr-image.yml
Labels: infrastruture

#284 Removed "ul ul a" from style.css.
  portal/static/css/style.css
Labels: bug
