Repository slateci/slate-portal, pull requests merged in 2023-01, with the labels that each got.

#204 Update to use gke collectors
  resources/chart/vars/values.yml
Labels: enhancement

#205 Gke opentel
  resources/chart/vars/values.yml
Labels: enhancement, infrastruture

#206 Add annotation for sidecar injection
  resources/chart/templates/deployment.yml
Labels: bug

#209 Tell Python to send stdout/stderr streams straight to terminal
  resources/chart/templates/secrets/portal-conf.yml
  resources/docker/Dockerfile
Labels: enhancement

#215 Added several new hard-coded blog posts to News dashboard card.
  portal/static/news.md
Labels: enhancement

#216 Implemented gunicorn
  main.py
  resources/docker/Dockerfile
  resources/docker/environment.yml
  resources/docker/requirements.txt
  resources/docker/scripts/docker-entrypoint.sh
  run_portal.py
Labels: enhancement

#217 Suppress errors from K8s health checks and Google LBs
  portal/templates/base.html
  portal/views/views_error_handling.py
Labels: enhancement

#219 Not logging anything for /healthz under not_found().
  portal/views/views_error_handling.py
Labels: enhancement

#221 Added new dictConfig() for logging to stdout.
  portal/__init__.py
  portal/views/views_error_handling.py
Labels: enhancement

#222 Convert Portal logging to JSON
  portal/__init__.py
  portal/logtools.py
  resources/docker/environment.yml
  resources/docker/requirements.txt
Labels: enhancement

#227 Gke autoinstruement 4
  resources/chart/templates/opentelemetry.yml
  resources/chart/vars/values.yml
Labels: bug
